### PR TITLE
Add omitDefautlDimension param

### PR DESCRIPTION
**Pull request by martrik**
## What did you implement:

Support a `omitDefaultDimension` parameter at the `alarm` level to avoid the `FunctionName` dimension that's added by default. This will allow the creation of alarms that aren't under the `AWS/Lambda` (API Gateway or SQS for example), which don't require the `FunctionName` dimension. This would address the following issues:
- #104
- #85 
- #19 

## How can we verify it:

Given that this is a relatively trivial change there's not much to verify. However, if you want to try creating an API Gateway alert you can use the following yaml configuration:
```yaml
 - name: function5XX
        description: '5XX response codes'
        namespace: 'AWS/ApiGateway'
        metric: 5XXError
        omitDefaultDimension: true
        dimensions:
          - Name: ApiName
            Value: api
          - Name: Resource
            Value: /api/endpoint
          - Name: Method
            Value: POST
          - Name: Stage
            Value: prod
        threshold: 5
        statistic: Sum
        period: 60
        evaluationPeriods: 1
        datapointsToAlarm: 1
        comparisonOperator: GreaterThanOrEqualToThreshold
```

If you check the alarm in CloudWatch you'll see that it doesn't include the `FunctionName` dimension.

## Todos:

- [X] Write tests
- [X] Write documentation
- [X] Fix linting errors
- [X] Provide verification config/commands/resources

### CODE REVIEW

**Comment by lkolchin** [comment]
Hey @martrik 
Excellent idea!
But a few gotchas in your PR.
I've created a default Alarm in the "alerts:" section like this - 
`      apiGw5XXError:
        description: 'Custom apiGw5XXError'
        namespace: 'AWS/ApiGateway'
        nameTemplate: $[functionName]-$[metricName]-apiGw5XXError
        metric: 5XXError
        omitDefaultDimension: true
        dimensions:
          - Name: ApiName
            Value: ${self:provider.stage}-${self:service}
          - Name: Stage
            Value: ${self:provider.stage}
        threshold: 5
        statistic: Sum
        period: 60
        evaluationPeriods: 1
        datapointsToAlarm: 1
        comparisonOperator: GreaterThanOrEqualToThreshold`

But I also have a bunch of lambdas sitting behind the same APIGW.
Meaning that if I enable it like this in the "alerts:" section:
`    alarms:
      - apiGw5XXError`

It will create alarms for each of my lambdas (for essentially the same metric) and that's not what I want. If I wanted to create alarm for each resource that would have made sense but if I want to do it for apigw only that's not gonna work.

There is also going to be a problem if you decide to create any other type of non lambda Alarms.
For SQS alarms for example you don't want to create lambda for the sake of creating alarm "functions: alarms:- name: SQSalarm"

You gotta de-couple "alarms:" from "functions:" to make this re-usable for any other types of alarms. 

Otherwise the workaround would be to put it under dummy or first lambda function stanza.
`functions:
  functionname:
    handler: states/states.get
    events:
      - http:
          path: path/{id}/{state}
          method: get
          cors: true
          private: true
    alarms:
      - name: apiGw5XXError
        namespace: 'AWS/ApiGateway'
        nameTemplate: $[functionName]-$[metricName]-apiGw5XXError # Optionally - naming template for the alarms, overwrites globally defined one
        metric: 5XXError
        omitDefaultDimension: true`

**Comment by martrik** [comment]
Thanks for the comment @lkolchin . The plugin as it is now doesn't support global alerts that are created just once, so it is true that you would need to add them to one lambda. I don't think that's a big deal though.

**Comment by Ali-Dalal** [comment]
Hi guys,

Thanks for the plugin.

I face the same issue where the plugin adds the function name when I need only to create an API gateway metric

```
{
    "metrics": [
        [ "AWS/ApiGateway", "5XXError", "FunctionName", myapp-staging-app", { "stat": "Sum" } ]
    ],
    "view": "timeSeries",
    "stacked": false,
    "period": 300,
    "region": "xxxxx"
}
```

as we can see the function name exists.

can you help please so I can build alerts for the API gateway?

Thanks

**Comment by rajgour** [comment]
Worked like a charm for SQS with workaround. One stop shop for all the alarms. Great work.
When will this be released? 

```
- name: customSQSAlarm
        description: 'Custom SQS Alarm'
        nameTemplate: $[functionName]-SQS-$[metricName]
        namespace: 'AWS/SQS'
        metric: NumberOfMessagesSent
        threshold: 5
        statistic: Sum
        period: 300
        evaluationPeriods: 5
        datapointsToAlarm: 1
        comparisonOperator: GreaterThanOrEqualToThreshold
        omitDefaultDimension: true
        dimensions:
          - Name: QueueName
            Value: test-alert-queue
```

**Comment by martrik** [comment]
It looks like this plugin isn't really maintained anymore. I've personally forked it and started adding improvements such as the one in this PR, as well as to allow alarms based on multiple metrics (for availability for instance).

I'm  interested to know if any of you would like me to release my fork publicly so that we can iterate on it without having to wait for months for the current maintainers to approve our PRs. I'd be willing to be an active maintainer and receive help from others.

**Comment by rajgour** [comment]
Please do. Let us know once done.

**Comment by palafoxernesto** [comment]
> It looks like this plugin isn't really maintained anymore. I've personally forked it and started adding improvements such as the one in this PR, as well as to allow alarms based on multiple metrics (for availability for instance).
> 
> I'm interested to know if any of you would like me to release my fork publicly so that we can iterate on it without having to wait for months for the current maintainers to approve our PRs. I'd be willing to be an active maintainer and receive help from others.

I'm ready to help you @martrik !

**Comment by JacoboGallardo** [comment]
Will this PR ever be merged?

I'm willing to help you as well, @martrik

**Comment by bulkan** [comment]
@JacoboGallardo not sure anymore as I'm not a collaborator on this project (I don't work at ACG anymore). 

Perhaps @adikari can help ?

**Comment by swrap** [comment]
I have been using the forked repo for this PR, everything seems to be running fine. Would love to get this PR merged as well. I believe this has to do with #111. It would be wonderful to get some feedback on either.

**Comment by t-zhao** [comment]
A work around could be using https://github.com/weixu365/serverless-scriptable-plugin
Add a `after:package:compileEvents` hook with the script
`const resources = serverless.service.provider.compiledCloudFormationTemplate.Resources;

/**
 * Remove the FunctionName dimension for the given AWS::CloudWatch::Alarm
 * So that serverless-plugin-aws-alerts could work for non-lambda alarts
 * @param {*} resource - The cfn resource instance
 */
function removeFunctionNameDimensionForAlarm(resource) {
  const index = resource.Properties.Dimensions.findIndex((dimension) => {
    return dimension.Name === 'FunctionName';
  });
  if (index > -1) {
    resource.Properties.Dimensions.splice(index, 1);
  }
}

removeFunctionNameDimensionForAlarm(resources['non_lambda_alarm_name']);
`

**Comment by adikari** [comment]
I have merged this and created a new release. However, having some trouble with publishing to NPM. Hopefully I can prepare an NPM release soon.

**Comment by bulkan** [comment]
Hey @adikari to give you a quick hand;

This repo was setup a while back by John to do auto [deploy publish](https://docs.travis-ci.com/user/deployment/npm/#npm-auth-token) to npm and the token has expired [now](https://github.com/ACloudGuru/serverless-plugin-aws-alerts/blob/master/.travis.yml#L17).

**Comment by adikari** [comment]
Thanks @bulkan .i have messaged @johncmckim to get me access to the npm so I could update the token.

**Pull request merged**
