### PR TITLE
Handle treatMissingData

### PR DESCRIPTION
**Pull request by chrishiste**
Just added the code and updated the test to handle missingData.

I tested it and it works like a charm ;)

https://github.com/ACloudGuru/serverless-plugin-aws-alerts/issues/

P.S : sorry about the hard to understand diff, you should definitely start using https://github.com/prettier/prettier

### CODE REVIEW

**Comment by johncmckim** [comment]
Nice work @chrishiste thanks for contributing. Don't worry about the diff I had assumed I had an editorconfig, but I must not have put that in. I've added a new issue #27 

The code looks good. But can you update the `README` with the new property? Once that is done I'll merge it in.

Thanks again!

**Comment by chrishiste** [comment]
@johncmckim Done, let me know if you need something else, cheers !

**Comment by chrishiste** [comment]
@johncmckim Hello, sorry but I noticed you haven't released the update, is there any reason why ? Maybe I can help ?

**Comment by johncmckim** [comment]
@chrishiste I hadn't published a new version because there's some changes I'd like to make re editor config ect. Working on that tonight and I'll release a new version soon.

**Comment by chrishiste** [comment]
No worries, thanks !

**Pull request merged**
