### PR TITLE
Allow specifying template(s) to use for dashboard(s)

### PR DESCRIPTION
**Pull request by bdgamble**
## What did you implement:

Make dashboards config accept template name(s) as a value. Can be an array if you want to create multiple dashboards.  Default dashboard is used if true is passed as value, and all dashboards that are not default, append the template name to the DashboardName. Add vertical template to include IteratorAge (p50 and p90 timeline, avg for numbers) and add numbers widgets for api-gw latency (avg), api-gw requests (sum), and lambda duration (avg). Vertical layout thas one metric per row, split evenly for the timeline and numbers widgets to show more data.

## How did you implement it:

pass the dashboards config to the compileDashboards function, if true then use default, otherwise make an array of dashboard templates passed and enumerate them to create the dashboard and add to cfResources. Created vertical template and added numbers widgets for the metrics that didn't have them, ensure all lambda and api-gw widgets were in the vertical dashboard, and that each metric split the two widgets (timeline and numbers) evenly across the row.

## How can we verify it:

deploy a service with this plugin with dashboards set to the array of 'default' and 'vertical', record some activity in the service, and then view the dashboard in Cloudwatch to see the new layout and widgets

default:
screen shot 2017-07-20 at 11 57 04 am

vertical:
screen shot 2017-07-20 at 11 59 47 am

## Todos:

- [ ] Write tests
- [ ] Write documentation
- [x] Fix linting errors
- [ ] Provide verification config/commands/resources

### CODE REVIEW

**Comment by johncmckim** [comment]
@bdgamble can you add a screenshot of the dashboard? I'm open to changing the default. I'd just like to see how it looks visually.

**Comment by bdgamble** [comment]
Sure thing, I'll put together a test service to showcase the new look

**Comment by bdgamble** [comment]
Updated with before and after, I'm open to tweaking the layout but like having the timeline and numbers for each metric beside each other so that you can see trends and also be able to quickly see roughly what the numbers are like without drilling into the graph, and keeping each row specific to one metric

**Comment by johncmckim** [comment]
@bdgamble I think that dashboard would be a great pre-set to have. But I'd prefer to keep the existing layout as the default.

Can you copy your `default.json` to a new file and keep the original layout config? Perhaps `vertical.json`?

We can then add support for selecting a dashboard by name layout by name.

**Comment by bdgamble** [comment]
@johncmckim I have updated the PR to have my layout as a separate template (vertical.json) and have added support for specifying the template (or templates if you use array syntax) for the dashboards to use. default still maps to the same named dashboard (in cf and cloudwatch)

**Pull request merged**
