### PR TITLE
Allow deploying alert resources to an external CloudFormation stack

### PR DESCRIPTION
**Pull request by kennu**
This adds an option to deploy all the alert resources to a separate CloudFormation stack.

The problem with deploying to just one CloudFormation stack is that you quickly hit the 200 resource limit if you have several Lambda functions. By using this option the number of resources in the main stack is not increased, because everything can be deployed to a separate stack.

Some small magic is performed to automatically replace Ref references with actual Lambda function names, and to remove some DependsOn elements (because the main stack will already have been deployed).

You can enable the option with `externalStack: true` or `--alerts-external-stack`. When not enabled, everything should work as previously. When the option is enabled, the external stack is automatically created on `sls deploy` and removed on `sls remove`.

### CODE REVIEW

**Comment by adikari** [comment]
@kennu Can you pls fix the status checks so I can merge this?

**Comment by kennu** [comment]
Hi, sorry, I'm not using this component now. The PR was made two years ago.

**Comment by adikari** [comment]
All good. Closing the PR.

**Comment by adikari** [comment]
This is deployed in #127

**Pull request closed without merging**
