### PR TITLE
initial changes adding log metric filters

### PR DESCRIPTION
**Pull request by jcdietrich**

### CODE REVIEW

**Comment by johncmckim** [comment]
Hi @jcdietrich thanks for contributing. Can you explain a little bit what this PR does? Next time, before creating a PR, could you create an issue first to discuss the bug/feature that you need.

**Comment by jcdietrich** [comment]
Hi, sorry about my lack of protocol. I will be sure to log an issue first in the future. 
What I need to do is create log metric filters (search a log for a pattern and have a metric fire on a match) They require a little more setup to the CF template, and unfortunately do no support dimensions. :(

**Comment by johncmckim** [comment]
No worries @jcdietrich. Sorry I haven't had a chance to look at this yet. I hope to look at it soon.

**Comment by jcdietrich** [comment]
Closing this one and will open another with some cleanup and tests.

**Comment by johncmckim** [comment]
Sounds good @jcdietrich. I really like the `pattern` filter. But I'm not sure `bunyanWarnings` and `bunyanErrors` should be in the default definition. They seem more application specific.

**Pull request closed without merging**
